name: DockerCI

on: [push, pull_request]
    
jobs:
  develop:
    runs-on: ubuntu-latest
    steps:
    - name: Build the Docker image
      run: docker build . --file Dockerfile

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install docker-compose
      uses: hoverkraft-tech/compose-action@v2.0.1
      with:
        compose-file: "./docker-compose.yml"
    - name: execute tests docker compose
      run: |
          docker-compose up
